### ISSUE TITLE
Add support over IPv6 ipset entry

### ISSUE THREAD

**Issue by leiless** [missdeer/ipset#1]
The [`ResponseReverter. WriteMsg()`](https://github.com/missdeer/ipset/blob/master/reverter.go#L32) will iterate all `A` and `AAAA` answer records and add them into ipset list.

Yet AFAIK, [`addIP()`](https://github.com/missdeer/ipset/blob/master/addip_linux.go#L21) will only work for one ipset type, i.e. `inet` or `inet6`, so you'll get `netfilter query: netlink receive: errno 4097` error if you mix one type with another.

I presumably thought you wanted to support over `IPv4`, please consider support over `IPv6`.
It seems needs you to add an extra argument to `ipset` since we can't determine which the ipset type is.

Or, we can do even better, check the ipset type on-the-fly, and add `A`, `AAAA` records respectively.
It seems https://pkg.go.dev/github.com/digineo/go-ipset/v2?tab=doc#Conn.Type can do this work.

**Comment by missdeer** [comment]
https://github.com/missdeer/ipset/commit/c61a7e9c9ba3c53f2dd85283582fd6d0356924a7
